#!/usr/bin/env bash
# Displays numbers 1-100 with FizzBuzz
for ((i=1; i<=100; i++))
do
    if [ $((i % 15)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $((i % 3)) -eq 0 ]
    then
        echo "Fizz"
    elif [ $((i % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
        echo "$i"
    fi
done
